curl --request POST \
    --header 'content-type: application/json' \
    --url http://localhost:4000/ \
    --data '{"query":"mutation {\n  getMessage(table: \"user3\") {\n    table\n  }\n}","variables":"{\r\n}"}'