curl --request POST \
    --header 'authentication: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiR2VsYXJkaW5pbyIsImlhdCI6MTYyOTg5OTY2MSwiZXhwIjoxNjI5OTAzMjYxfQ.gHDm6XKn3UZ968pomzbtcFJTZMckRWORo2dffSgTB4g' \
    --header 'content-type: application/json' \
    --url http://localhost:4000/ \
    --data '{"query":"query Query($getMessageChatName: String) {\n  getMessage(chatName: $getMessageChatName) {\n    message\n    sentBy\n    sendDate\n  }\n}","variables":"{\r\n  \"getMessageChatName\": \"FirstChat\"\r\n}"}'